const KEBAB_CASE: 'KEBAB_CASE' = 'KEBAB_CASE';
const CAMEL_CASE: 'CAMEL_CASE' = 'CAMEL_CASE';
const PASCAL_CASE: 'PASCAL_CASE' = 'PASCAL_CASE';
const SNAKE_CASE: 'SNAKE_CASE' = 'SNAKE_CASE';
const UPPER_CASE: 'UPPER_CASE' = 'UPPER_CASE';
const LOWER_CASE: 'LOWER_CASE' = 'LOWER_CASE';
const CAPITAL_CASE: 'CAPITAL_CASE' = 'CAPITAL_CASE';
const CONSTANT_CASE: 'CONSTANT_CASE' = 'CONSTANT_CASE';
const TITLE_CASE: 'TITLE_CASE' = 'TITLE_CASE';
const SENTENCE_CASE: 'SENTENCE_CASE' = 'SENTENCE_CASE';

const stringUtilsConstants = {
	KEBAB_CASE,
	CAMEL_CASE,
	PASCAL_CASE,
	SNAKE_CASE,
	UPPER_CASE,
	LOWER_CASE,
	CAPITAL_CASE,
	CONSTANT_CASE,
	TITLE_CASE,
	SENTENCE_CASE,
};

export default stringUtilsConstants;
