enum NewsItemContextConstants {
	INIT_GET_COMMENTS_PENDING = 'INIT_NEWS_ITEM_GET_COMMENTS_PENDING',
	INIT_GET_COMMENTS_SUCCESS = 'INIT_NEWS_ITEM_GET_COMMENTS_SUCCESS',
	INIT_GET_COMMENTS_FAIL = 'INIT_NEWS_ITEM_GET_COMMENTS_FAIL',

	GET_MORE_MAIN_COMMENTS_PENDING = 'NEWS_ITEM_GET_MORE_MAIN_COMMENTS_PENDING',
	GET_MORE_MAIN_COMMENTS_SUCCESS = 'NEWS_ITEM_GET_MORE_MAIN_COMMENTS_SUCCESS',
	GET_MORE_MAIN_COMMENTS_FAIL = 'NEWS_ITEM_GET_MORE_MAIN_COMMENTS_FAIL',

	GET_MORE_MAIN_COMMENT_REPLIES_PENDING = 'NEWS_ITEM_GET_MORE_MAIN_COMMENT_REPLIES_PENDING',
	GET_MORE_MAIN_COMMENT_REPLIES_SUCCESS = 'NEWS_ITEM_GET_MORE_MAIN_COMMENT_REPLIES_SUCCESS',
	GET_MORE_MAIN_COMMENT_REPLIES_FAIL = 'NEWS_ITEM_GET_MORE_MAIN_COMMENT_REPLIES_FAIL',

	INIT_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_PENDING = 'INIT_GET_NEWS_ITEM_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_PENDING',
	INIT_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_SUCCESS = 'INIT_GET_NEWS_ITEM_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_SUCCESS',
	INIT_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_FAIL = 'INIT_GET_NEWS_ITEM_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_FAIL',

	CREATE_PENDING = 'NEWS_ITEM_CREATE_PENDING',
	CREATE_SUCCESS = 'NEWS_ITEM_CREATE_SUCCESS',
	CREATE_FAIL = 'NEWS_ITEM_CREATE_FAIL',
}

export default NewsItemContextConstants;
