enum NewsItemContextConstants {
	ADD_REPLIES_TO_COMMENT_MAIN = 'ADD_REPLIES_TO_COMMENT_MAIN',
	ADD_NEW_MAIN_OR_MAIN_REPLY_COMMENT = 'ADD_NEW_MAIN_OR_MAIN_REPLY_COMMENT',
	UPDATE_MAIN_OR_MAIN_REPLY_COMMENT = 'NEWS_ITEM_UPDATE_MAIN_OR_MAIN_REPLY_COMMENT',
	DELETE_MAIN_OR_MAIN_REPLY_COMMENT = 'DELETE_MAIN_OR_MAIN_REPLY_COMMENT',

	UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_PENDING = 'NEWS_ITEM_UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_PENDING',
	UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_SUCCESS = 'NEWS_ITEM_UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_SUCCESS',
	UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_FAIL = 'NEWS_ITEM_UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_FAIL',

	INIT_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_PENDING = 'INIT_GET_NEWS_ITEM_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_PENDING',
	INIT_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_SUCCESS = 'INIT_GET_NEWS_ITEM_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_SUCCESS',
	INIT_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_FAIL = 'INIT_GET_NEWS_ITEM_TYPE_BLOG_DETAILS_TYPE_CONTENT_CONTENT_FAIL',

	CREATE_NEW_NEWS_ITEM = 'CREATE_NEW_NEWS_ITEM',
	UPDATE_NEWS_ITEM = 'UPDATE_NEWS_ITEM',

	DELETE_PENDING = 'NEWS_ITEM_DELETE_PENDING',
	DELETE_SUCCESS = 'NEWS_ITEM_DELETE_SUCCESS',
	DELETE_FAIL = 'NEWS_ITEM_DELETE_FAIL',
	DELETE_RESET = 'NEWS_ITEM_DELETE_RESET',
}

export default NewsItemContextConstants;
