export enum UserProfilePageConstants {
	SET_VISITOR_STATUS_PENDING = 'SET_PROFILE_PAGE_VISITOR_STATUS_PENDING',
	SET_VISITOR_STATUS_SUCCUSS = 'SET_PROFILE_PAGE_VISITOR_STATUS_SUCCUSS',
	SET_VISITOR_STATUS_FAIL = 'SET_PROFILE_PAGE_VISITOR_STATUS_FAIL',
}

export default UserProfilePageConstants;
