export const SET_DATA_FIRST_TIME = 'SET_DATA_FIRST_TIME';
export const SET_DATA = 'SET_DATA';
export const RESET_DATA = 'RESET_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_DATA_TO_THE_LATEST = 'UPDATE_USER_DATA_TO_THE_LATEST';

const types = {
	SET_DATA_FIRST_TIME,
	SET_DATA,
	RESET_DATA,
	UPDATE_USER_DATA,
	UPDATE_USER_DATA_TO_THE_LATEST,
};

export default types;
