enum NewsContextConstants {
	GET_MORE_ITEMS_PENDING = 'GET_MORE_NEWS_ITEMS_PENDING',
	GET_MORE_ITEMS_SUCCESS = 'GET_MORE_NEWS_ITEMS_SUCCESS',
	GET_MORE_ITEMS_FAIL = 'GET_MORE_NEWS_ITEMS_FAIL',
}

export default NewsContextConstants;
