enum ECommentConstants {
	/*
	INIT_GET_COMMENTS_PENDING = 'INIT_NEWS_ITEM_GET_COMMENTS_PENDING',
	INIT_GET_COMMENTS_SUCCESS = 'INIT_NEWS_ITEM_GET_COMMENTS_SUCCESS',
	INIT_GET_COMMENTS_FAIL = 'INIT_NEWS_ITEM_GET_COMMENTS_FAIL',

	GET_MORE_MAIN_COMMENTS_PENDING = 'NEWS_ITEM_GET_MORE_MAIN_COMMENTS_PENDING',
	GET_MORE_MAIN_COMMENTS_SUCCESS = 'NEWS_ITEM_GET_MORE_MAIN_COMMENTS_SUCCESS',
	GET_MORE_MAIN_COMMENTS_FAIL = 'NEWS_ITEM_GET_MORE_MAIN_COMMENTS_FAIL',

	GET_MORE_MAIN_COMMENT_REPLIES_PENDING = 'NEWS_ITEM_GET_MORE_MAIN_COMMENT_REPLIES_PENDING',
	GET_MORE_MAIN_COMMENT_REPLIES_SUCCESS = 'NEWS_ITEM_GET_MORE_MAIN_COMMENT_REPLIES_SUCCESS',
	GET_MORE_MAIN_COMMENT_REPLIES_FAIL = 'NEWS_ITEM_GET_MORE_MAIN_COMMENT_REPLIES_FAIL',
  */

	CREATE_REPLY_FOR_MAIN_COMMENT = 'CREATE_REPLY_FOR_MAIN_COMMENT',
	CREATE_REPLY_FOR_MAIN_COMMENT_PENDING = 'CREATE_REPLY_FOR_MAIN_COMMENT_PENDING',
	CREATE_REPLY_FOR_MAIN_COMMENT_SUCCESS = 'CREATE_REPLY_FOR_MAIN_COMMENT_SUCCESS',
	CREATE_REPLY_FOR_MAIN_COMMENT_FAIL = 'CREATE_REPLY_FOR_MAIN_COMMENT_FAIL',

	UPDATE_MAIN_OR_MAIN_REPLY_COMMENT = 'UPDATE_MAIN_OR_MAIN_REPLY_COMMENT',
	UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_PENDING = 'UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_PENDING',
	UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_SUCCESS = 'UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_SUCCESS',
	UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_FAIL = 'UPDATE_MAIN_OR_MAIN_REPLY_COMMENT_FAIL',

	DELETE_MAIN_OR_MAIN_REPLY_COMMENT = 'DELETE_MAIN_OR_MAIN_REPLY_COMMENT',
	DELETE_MAIN_OR_MAIN_REPLY_COMMENT_PENDING = 'DELETE_MAIN_OR_MAIN_REPLY_COMMENT_PENDING',
	DELETE_MAIN_OR_MAIN_REPLY_COMMENT_SUCCESS = 'DELETE_MAIN_OR_MAIN_REPLY_COMMENT_SUCCESS',
	DELETE_MAIN_OR_MAIN_REPLY_COMMENT_FAIL = 'DELETE_MAIN_OR_MAIN_REPLY_COMMENT_FAIL',

	GET_REPLIES_FOR_MAIN_COMMENT = 'GET_REPLIES_FOR_MAIN_COMMENT',
	GET_REPLIES_FOR_MAIN_COMMENT_PENDING = 'GET_REPLIES_FOR_MAIN_COMMENT_PENDING',
	GET_REPLIES_FOR_MAIN_COMMENT_SUCCESS = 'GET_REPLIES_FOR_MAIN_COMMENT_SUCCESS',
	GET_REPLIES_FOR_MAIN_COMMENT_FAIL = 'GET_REPLIES_FOR_MAIN_COMMENT_FAIL',
}

export default ECommentConstants;
