enum ENewsItemExtraData {
	ADD_MAIN_COMMENTS = 'ADD_MAIN_COMMENTS',
	ADD_REPLIES_TO_COMMENT_MAIN = 'ADD_REPLIES_TO_COMMENT_MAIN',
	ADD_NEW_MAIN_OR_MAIN_REPLY_COMMENT = 'ADD_NEW_MAIN_OR_MAIN_REPLY_COMMENT',
	UPDATE_MAIN_OR_MAIN_REPLY_COMMENT = 'UPDATE_MAIN_OR_MAIN_REPLY_COMMENT',
	DELETE_MAIN_OR_MAIN_REPLY_COMMENT = 'DELETE_MAIN_OR_MAIN_REPLY_COMMENT',
}

export default ENewsItemExtraData;
