enum ECommentConstants {
	GET_COMMENTS_MAIN = 'GET_COMMENTS_MAIN',
	GET_COMMENTS_MAIN_PENDING = 'GET_COMMENTS_MAIN_PENDING',
	GET_COMMENTS_MAIN_SUCCESS = 'GET_COMMENTS_MAIN_SUCCESS',
	GET_COMMENTS_MAIN_FAIL = 'GET_COMMENTS_MAIN_FAIL',

	CREATE_MAIN_COMMENT = 'CREATE_MAIN_COMMENT',
	CREATE_MAIN_COMMENT_PENDING = 'CREATE_MAIN_COMMENT_PENDING',
	CREATE_MAIN_COMMENT_SUCCESS = 'CREATE_MAIN_COMMENT_SUCCESS',
	CREATE_MAIN_COMMENT_FAIL = 'CREATE_MAIN_COMMENT_FAIL',
}

export default ECommentConstants;
