enum ECommentConstants {
	INIT_GET_COMMENTS_MAIN = 'INIT_GET_COMMENTS_MAIN',
	INIT_GET_COMMENTS_MAIN_PENDING = 'INIT_GET_COMMENTS_MAIN_PENDING',
	INIT_GET_COMMENTS_MAIN_SUCCESS = 'INIT_GET_COMMENTS_MAIN_SUCCESS',
	INIT_GET_COMMENTS_MAIN_FAIL = 'INIT_GET_COMMENTS_MAIN_FAIL',

	CREATE_MAIN_COMMENT = 'CREATE_MAIN_COMMENT',
	CREATE_MAIN_COMMENT_PENDING = 'CREATE_MAIN_COMMENT_PENDING',
	CREATE_MAIN_COMMENT_SUCCESS = 'CREATE_MAIN_COMMENT_SUCCESS',
	CREATE_MAIN_COMMENT_FAIL = 'CREATE_MAIN_COMMENT_FAIL',
}

export default ECommentConstants;
