enum ECommentConstants {
	CREATE_MAIN_COMMENT = 'CREATE_MAIN_COMMENT',
	CREATE_MAIN_COMMENT_PENDING = 'CREATE_MAIN_COMMENT_PENDING',
	CREATE_MAIN_COMMENT_SUCCESS = 'CREATE_MAIN_COMMENT_SUCCESS',
	CREATE_MAIN_COMMENT_FAIL = 'CREATE_MAIN_COMMENT_FAIL',
}

export default ECommentConstants;
