import { generateCommonTags } from './utils';

export const generateFractalTreeTool = {
	relativePath: 'fractal-tree',
	title: 'Generate Beautiful Fractal Trees with Our Online Tool',
	shortTitle: 'Fractal Tree Generator',
	description:
		'Our online tool allows you to generate stunning fractal trees with custom parameters or randomly generated values. Explore the infinite possibilities of fractal tree design and create your own unique creations!',
	shortDescription:
		'Generate beautiful fractal trees with custom or random parameters with our online tool.',
	Tags: [
		'fractal-tree',
		'generator',
		'computer-generated-arts',
		'generate',
		'random',
		'design',
		'unique',
		...generateCommonTags()
	],
	faqs: [
		{
			question: 'How do I use the fractal tree generator?',
			answer:
				'Simply enter your desired parameters or choose to generate a random tree, and hit the "Generate" button to see your fractal tree design.'
		},
		{
			question: 'Can I customize the parameters of my fractal tree?',
			answer:
				'Yes, you can adjust the branch length, branch angle, and recursion depth to create the exact fractal tree you want.'
		},
		{
			question: 'Can I save my fractal tree designs?',
			answer:
				'Yes, you can download your fractal tree as an image file or save it to your account for later use.'
		},
		{
			question: 'How many different fractal tree designs can I create?',
			answer:
				'With the customizable parameters and the ability to generate random trees, the possibilities are virtually infinite. Explore and create your own unique fractal tree designs.'
		},
		{
			question: 'Is the fractal tree generator free to use?',
			answer: 'Yes, our fractal tree generator is completely free to use.'
		},
		{
			question: 'Is the fractal tree generator mobile-friendly?',
			answer:
				'Yes, our fractal tree generator is fully optimized for use on mobile devices.'
		},
		{
			question: 'Are there any limitations to the fractal tree generator?',
			answer:
				'There are no limitations to the number of fractal trees you can generate or the parameters you can use. Explore and create as many designs as you like.'
		},
		{
			question:
				'Can I share my fractal tree designs on social media or other platforms?',
			answer:
				"Yes, you can share your fractal tree designs on social media or other platforms by saving the design and uploading it to the platform of your choice, just don't forget to give us the credit"
		},
		{
			question:
				'How do I know which parameters will create the best fractal tree design?',
			answer:
				'Experimenting with different parameter values and previewing the generated fractal tree can help you determine which parameters will create the best design for your needs.'
		},
		{
			question: 'Can I use the fractal tree generator for commercial purposes?',
			answer:
				"Yes, you can use the fractal tree generator for commercial purposes, just don't forget to give us the credit."
		},
		{
			question:
				'How is the random fractal tree generator different from using custom parameters?',
			answer:
				'The random fractal tree generator creates a unique fractal tree design using randomly generated values for the parameters, while using custom parameters allows you to specify specific values for the parameters to generate a fractal tree.'
		},
		{
			question: 'How do I know if my fractal tree design is unique?',
			answer:
				'You can compare your fractal tree design to other designs generated by the tool to determine if it is unique, or you can use a search engine to check if the design has been used elsewhere online.'
		},
		{
			question: 'How does the fractal tree generator ensure unique designs?',
			answer:
				'The fractal tree generator uses advanced algorithms to generate unique designs based on the parameters or random values inputted.'
		},
		{
			question: 'How does the depth of the fractal tree affect its appearance?',
			answer:
				'The depth of the fractal tree affects its appearance by determining how many iterations of the branching pattern are drawn. A deeper fractal tree will have more branches and a more complex appearance, while a shallower tree will have fewer branches and a simpler appearance.'
		},
		{
			question:
				'What are some creative ways to use fractal trees in design projects?',
			answer:
				'Some creative ways to use fractal trees in design projects include using them as backgrounds, incorporating them into logos or graphics, and using them as inspiration for hand-drawn art.'
		}
	]
};

const cgArtsTools = {
	relativePath: 'cg-arts',
	title: 'Explore the World of Computer Generated Arts with Our Online Tools',
	shortTitle: 'Explore Computer Generated Art with Our Online Tools',
	description:
		"Get creative with our collection of online tools for generating computer-generated art. From fractal trees to abstract patterns, there's something for everyone to enjoy. Experiment with customizable parameters or let the computer do the work for you with randomly generated designs. Plus, get answers to common questions about computer-generated art in our Q&A section.",
	shortDescription:
		'Discover the endless possibilities of computer generated art with our collection of online tools. Create your own unique designs with customizable options, or explore randomly generated art. Get inspired and learn more with our helpful Q&As.',
	pages: [generateFractalTreeTool],
	faqs: [] as {
		question: string;
		answer: string;
	}[],
	Tags: ['']
};

export default cgArtsTools;
