import type { NextPage } from 'next';

import Head from 'next/head';
import CreativeWorksFeed from '@components/shared/core/CreativeWorks/Feed';
import { useTypedSession } from '@utils/common/hooks';
import { CreativeWorkType } from '@prisma/client';

const Home: NextPage = () => {
	const { data: session, status } = useTypedSession();

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<section className='section-p'>
				{/* <header>
					<h1 className='text-h1'>{hello.data?.greeting}</h1>
				</header> */}
				<div className='md:w-3/5'>
					<CreativeWorksFeed
						getAllCreativeWorksInput={{
							authorId: session?.user.id,
							checkForPrivileges: status === 'authenticated',
							type: [CreativeWorkType.BLOG_POST]
						}}
					/>
				</div>
			</section>
		</>
	);
};

export default Home;
