export const ALL = 'ALL';
export const ONE = 'ONE';
export const ARTICLES = 'ARTICLES';
export const POSTS = 'POSTS';

export const INIT_STATE = 'INIT_STATE';
export const ADDING_USER_ONE_NEWS_ITEM_TO_NEWS =
	'ADDING_USER_ONE_NEWS_ITEM_TO_NEWS';
export const UPDATING_USER_ONE_NEWS_ITEM_IN_NEWS =
	'UPDATING_USER_ONE_NEWS_ITEM_IN_NEWS';
export const DELETING_USER_ONE_NEWS_ITEM_IN_NEWS =
	'DELETING_USER_ONE_NEWS_ITEM_IN_NEWS';

export const ADD_CONTENT_TO_NEWS_ITEM = 'ADD_CONTENT_TO_NEWS_ITEM';

export const ADD_COMMENTS_TO_NEWS_ITEM = 'ADD_COMMENTS_TO_NEWS_ITEM';
export const ADD_COMMENT_TO_NEWS_ITEM_AFTER_POSTING =
	'ADD_COMMENT_TO_NEWS_ITEM_AFTER_POSTING';
export const LOADING_COMMENT_REPLIES_IN_A_NEWS_ITEM =
	'LOADING_COMMENT_REPLIES_IN_A_NEWS_ITEM';
export const ADDING_REPLY_TO_A_MAIN_COMMENT_OR_A_REPLY_TO_A_COMMENT_IN_A_NEWS_ITEM =
	'ADDING_REPLY_TO_A_MAIN_COMMENT_OR_A_REPLY_TO_A_COMMENT_IN_A_NEWS_ITEM';
export const UPDATING_A_MAIN_OR_A__REPLY_COMMENT_IN_A_NEWS_ITEM =
	'UPDATING_A_MAIN_OR_A__REPLY_COMMENT_IN_A_NEWS_ITEM';
export const DELETING_A_MAIN_OR_A__REPLY_COMMENT_IN_A_NEWS_ITEM =
	'DELETING_A_MAIN_OR_A__REPLY_COMMENT_IN_A_NEWS_ITEM';

export const ADD_USER_VOTE_FOR_NEWS_ITEM = 'ADD_USER_VOTE_FOR_NEWS_ITEM';
export const DELETE_USER_VOTE_FOR_NEWS_ITEM = 'DELETE_USER_VOTE_FOR_NEWS_ITEM';
export const CHANGE_USER_VOTE_FOR_NEWS_ITEM = 'CHANGE_USER_VOTE_FOR_NEWS_ITEM';

export const LOAD_USER_VOTE_FOR_NEWS_ITEM = 'LOAD_USER_VOTE_FOR_NEWS_ITEM';

const types = {
	ALL,
	ONE,
	ARTICLES,
	POSTS,

	INIT_STATE,
	ADDING_USER_ONE_NEWS_ITEM_TO_NEWS,
	UPDATING_USER_ONE_NEWS_ITEM_IN_NEWS,
	DELETING_USER_ONE_NEWS_ITEM_IN_NEWS,

	ADD_CONTENT_TO_NEWS_ITEM,

	ADD_COMMENTS_TO_NEWS_ITEM,
	ADD_COMMENT_TO_NEWS_ITEM_AFTER_POSTING,
	LOADING_COMMENT_REPLIES_IN_A_NEWS_ITEM,
	ADDING_REPLY_TO_A_MAIN_COMMENT_OR_A_REPLY_TO_A_COMMENT_IN_A_NEWS_ITEM,
	UPDATING_A_MAIN_OR_A__REPLY_COMMENT_IN_A_NEWS_ITEM,
	DELETING_A_MAIN_OR_A__REPLY_COMMENT_IN_A_NEWS_ITEM,

	ADD_USER_VOTE_FOR_NEWS_ITEM,
	DELETE_USER_VOTE_FOR_NEWS_ITEM,
	CHANGE_USER_VOTE_FOR_NEWS_ITEM,

	LOAD_USER_VOTE_FOR_NEWS_ITEM,
};

export default types;
